//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalExamPurchaseOrderManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderLine
    {
        public int OrderNo { get; set; }
        public int PartNo { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Memo { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
