//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalExamPurchaseOrderManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder()
        {
            this.PurchaseOrderLines = new HashSet<PurchaseOrderLine>();
        }
    
        public int OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ETADate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> QtyOpen { get; set; }
        public Nullable<bool> SentEmail { get; set; }
        public Nullable<int> SupplierNo { get; set; }
        public Nullable<int> StockSiteNo { get; set; }
        public string Note { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string PostCode { get; set; }
    
        public virtual StockSite StockSite { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; }
    }
}
